### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by hattan** [hattan/verify-linked-issue-action#16]
This release introduces :

* message input
```yaml
- name: Verify Linked Issue
  uses: hattan/verify-linked-issue-action@v1
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    message: 'Error! This is a custom error'
```
* filename input
```yaml
- name: Verify Linked Issue
  uses: ./ 
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    filename: 'example/templates/fail_comment.txt'
```

Another option for file templates is to exclude the filename and message inputs then add a file a the path: .github/VERIFY_PR_COMMENT_TEMPLATE.md
