### ISSUE TITLE
Custom regexp

### ISSUE THREAD

**Issue by Mats-Jakobsson** [hattan/verify-linked-issue-action#36]
Hi!

Fantastic initiative. I have a feature request though. Would it be possible to add the possibility to pass a custom regexp as an argument.

(In my case I would love to match on (<companyName>\/<SpecificRepo>\/)#(.*?)[0-9]+ since all my issues resides in one specific repo.)

So something like:

```
- name: Verify Linked Issue
  uses: hattan/verify-linked-issue-action@v1.1.5
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  with:
    regExp: "/(<companyName>\/<SpecificRepo>\/)#(.*?)[0-9]+/g"
    ```
    
Many thanks!
